### ISSUE TITLE
Issue when running docker_haproxy_harvest_scrape.sh

### ISSUE THREAD

**Issue by buzzkillionair** [GoSecure/freshonions-torscraper#19]
When I run the ```docker_haproxy_harvest_scrape.sh``` command, it spits out a few different things and then I get 2 hours of
```
 100  2197  100  2197    0     0   2034      0  0:00:01  0:00:01 --:--:--  2034
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to receive SOCKS5 connect request ack.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1249  100  1249    0     0   1881      0 --:--:-- --:--:-- --:--:--  1878
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2357  100  2357    0     0   1082      0  0:00:02  0:00:02 --:--:--  1082
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    156      0  0:00:01  0:00:01 --:--:--   156
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
```
 I was wondering how long this is supposed to take and if this seems right. Going to leave it running over night.  The web-service container also receives no data so it isn't saving anything into there.

**Comment by L3houx** [comment]
Hi @buzzkillionair, 

Normally, you are not supposed to start this script manually. Starting the docker-compose file will start all containers and start harvesting and scraping. Personally, I connect to the Torscraper container and I run manually the scraper because harvesting is a pretty long process. If you let the Torscraper running during a long time without interruption, you can only start the docker-compose file and let the magic happen.

The time depends on your list of onions. In your case, I see that there are several links that are not working (are not reachable). So, I would recommend you to remove them from your list to accelerate the process. Visit one by one and keep the ones that are reachable. I know that it can be long but normally a reachable site will respond rapidly. The other way you can "fix" the problem. Add a timeout to the curl request to stop the request if it takes more than X seconds. 

If you have any other questions don't hesitate.

**Comment by buzzkillionair** [comment]
@L3houx I did start by running ```docker-compose up``` which ended up being the attempt that took two hours so I decided to try running manually. I wanted to see if it would fix anything so I am going to try to get it to run manually overnight.

**Comment by L3houx** [comment]
@buzzkillionair 
Like I said, clean your list of site in harvest.sh. It will make a huge difference. Do not forget to update the container that contains the Torscraper to be sure it takes the last version of harvest.sh.

Keep me updated!

**Comment by buzzkillionair** [comment]
@L3houx I believe everything is up to date. I will keep you informed.

**Comment by buzzkillionair** [comment]
@L3houx  Is there a way to set a scraping time limit? I have a site that it connects to fairly quickly but takes hours to scrape and I want to set a timer for it.

**Comment by buzzkillionair** [comment]
Issue solved by deleting majority of websites in the dictionary.
