### ISSUE TITLE
What is "show fh default"

### ISSUE THREAD

**Issue by keldnorman** [GoSecure/freshonions-torscraper#9]
When searching there is an option called "show fh default" what is that ? 
found hosts ? or ?

**Comment by obilodeau** [comment]
According [to the code](https://github.com/GoSecure/freshonions-torscraper/blob/a95c008eb19367af23702fd65b2a1794ea40aae6/lib/helpers.py#L152):
```python
	if not context["show_fh_default"]:
		query = query.filter("d.is_crap == 0")
```

If it's turned off, crap domains are not displayed. Now what is a crap domain?

```python
    def before_insert(self):
        if (self.title.find("Site Hosted by Freedom Hosting II") != -1 or
            self.title.find("Freedom Hosting II - hacked") != -1 or
            self.title.find("This site is hosted by Freedom Hosting III") != -1 or
            self.title.find("The Onion Farm") != -1 or
            self.title.find("Site hosted by Daniel's hosting service") != -1):
            self.is_crap = True
```

Looks like the original developer didn't like these sites. Probably because they polluted the results. So FH would mean `Freedom Hosting`.

In our instance, enabling it shows around 300 more pages. Freedom Hosting [was apparently hacked and taken down](https://mascherari.press/onionscan-report-fhii-a-new-map-and-the-future/) somewhere in 2017.
